#!/bin/bash

# Initialize variables

INPUT_DIR_PATH=$1 # /home/trukhinmaksim/Maksim/Projects/cli/Project_2_directory-scanner/root
INPUT_DIR_NAME=$(basename "$INPUT_DIR_PATH")

IMG_OUTPUT_PATH=$2 # /home/trukhinmaksim/Maksim/Projects/cli/Project_2_directory-scanner/output/schm.png
IMG_OUTPUT_DIR_PATH=$(dirname "$IMG_OUTPUT_PATH")
IMG_OUTPUT_NAME=$(basename "$IMG_OUTPUT_PATH")

CODE_CREATOR_PATH="/home/dist/code_creator.o"
PLANTUML_JAR_PATH="/home/dist/plantuml.jar"

shift

ORIGINAL_ARGS=("$@")

COMMAND="$CODE_CREATOR_PATH /data/$INPUT_DIR_NAME ${ORIGINAL_ARGS[@]} | java -Djava.awt.headless=true -jar $PLANTUML_JAR_PATH -pipe > /output/$IMG_OUTPUT_NAME"



docker run \
    -it \
    --rm \
    -v "$INPUT_DIR_PATH:/data/$INPUT_DIR_NAME" \
    -v "$IMG_OUTPUT_DIR_PATH:/output" \
    dir_scanner_img:v11 \
    /bin/bash -c "$COMMAND"


if [ $? -eq 0 ]; then
    echo "Finished successfully."
else
    echo "Failed. Please check the output for errors."
    exit 1
fi
echo "--- Run Complete ---"