#!/bin/bash

# Initialize variables

INPUT_DIR_PATH=/home/trukhinmaksim/Maksim/Projects/cli/Project_2_directory-scanner/root
INPUT_DIR_NAME=root

IMG_OUTPUT_DIR_PATH=/home/trukhinmaksim/Maksim/Projects/cli/Project_2_directory-scanner/output
IMG_OUTPUT_NAME=schm.png

CODE_CREATOR_PATH="/home/dist/code_creator.o"
PLANTUML_JAR_PATH="/home/dist/plantuml.jar"

COMMAND="$CODE_CREATOR_PATH /data/$INPUT_DIR_NAME -b --color '#ff0000-#0000ff' | java -Djava.awt.headless=true -jar $PLANTUML_JAR_PATH -pipe > /output/$IMG_OUTPUT_NAME"



docker run \
    -it \
    --rm \
    -v "$INPUT_DIR_PATH:/data/$INPUT_DIR_NAME" \
    -v "$IMG_OUTPUT_DIR_PATH:/output" \
    dir_scanner_img:v11 \
    /bin/bash -c "$COMMAND"