#!/bin/bash

# Initialize variables

output_path="" # This variable will store the path

# Parse command-line arguments
while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -o)
            # Check if the next argument exists and is not another option
            if [[ -n "$2" && ! "$2" =~ ^- ]]; then
                output_path="$2"
                shift # Consume the argument value
            else
                echo "Error: Argument for $1 is missing or invalid."
                exit 1
            fi
            ;;
        *)
    esac
    shift # Consume the option
done

if [[ -z "$output_path" ]]; then
    echo "Usage: $0 -p <path>"
    echo "Example: $0 -p /home/user/documents"
    exit 1
fi

echo "Extracted path: $output_path"
filename=$(basename -- "$output_path")
extension="${filename##*.}"

CODE_CREATOR="./code_creator"
PLANTUML_SCRIPT="./plantuml"

$CODE_CREATOR /home/trukhinmaksim/Maksim/Projects/cli/Project_2_directory-scanner/root -t b | $PLANTUML_SCRIPT